### ISSUE TITLE
Add an option to disable device security

### ISSUE THREAD

**Issue by muecke36** [bgewehr/fronthem#1]
The per-device security is a nice feature but if it is not needed and you have a number of devices it makes usage very difficult. Also if IP Addresses change it is not optimal. I'd like to have an option to disable device security or define fronthem devices for whole subnets (e.g. identity = 192.168.127.*).

**Comment by bgewehr** [comment]
As this is a fork for UZSU optimizing only, please head over to github.com/herrmannj/fronthem with this issue. That is the main repository and the author of fronthem. Thx!
